"""initial migration

Revision ID: 53952c86700f
Revises: None
Create Date: 2015-03-22 16:55:27.780607

"""

# revision identifiers, used by Alembic.
revision = '53952c86700f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('github_id', sa.Unicode(), nullable=True),
    sa.Column('twitter_id', sa.Unicode(), nullable=True),
    sa.Column('facebook_id', sa.Unicode(), nullable=True),
    sa.Column('login', sa.Unicode(), nullable=True),
    sa.Column('display_name', sa.Unicode(), nullable=True),
    sa.Column('email', sa.Unicode(), nullable=True),
    sa.Column('api_key', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.Unicode(), nullable=True),
    sa.Column('label', sa.Unicode(), nullable=True),
    sa.Column('ignore_case', sa.Boolean(), nullable=True),
    sa.Column('match_aliases', sa.Boolean(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('normalize_text', sa.Boolean(), nullable=True),
    sa.Column('enable_invalid', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Enum('read', 'edit', 'manage', name='roles'), nullable=False),
    sa.Column('dataset_id', sa.String(length=25), nullable=True),
    sa.Column('user_id', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('context',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.Unicode(), nullable=True),
    sa.Column('publisher', sa.Unicode(), nullable=True),
    sa.Column('publisher_url', sa.Unicode(), nullable=True),
    sa.Column('user_submitted', sa.Boolean(), nullable=True),
    sa.Column('dataset_id', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mimetype', sa.Unicode(), nullable=True),
    sa.Column('filename', sa.Unicode(), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('dataset_id', sa.String(length=25), nullable=True),
    sa.Column('creator_id', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statement',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('subject', sa.String(length=25), nullable=True),
    sa.Column('attribute', sa.String(length=1024), nullable=True),
    sa.Column('value', sa.Unicode(), nullable=True),
    sa.Column('dataset_id', sa.String(length=25), nullable=True),
    sa.Column('context_id', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['context_id'], ['context.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    pass
